/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class FrmInventario extends javax.swing.JFrame implements ItfFrmInventario {

    private List<DetalleCompra> ldcfinal = new LinkedList<>();
    private List<DetalleVenta> ldvfinal = new LinkedList<>();

    /**
     * Creates new form FrmInventario
     */
    public FrmInventario() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        txtidproducto.setEditable(false);
        BuscarProducto bp = new BuscarProducto();
        bp.start();
    }

    @Override
    public void setLdcfinal(List<DetalleCompra> ldcfinal) {
        this.ldcfinal = ldcfinal;
    }

    @Override
    public void setLdvfinal(List<DetalleVenta> ldvfinal) {
        this.ldvfinal = ldvfinal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtvalunitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmemoriainterna = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtmemoriaexterna = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtprocesador = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbgama = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextnomProduc = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setEnabled(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transfer_77884.png"))); // NOI18N
        jButton1.setText("Compras");
        jButton1.setToolTipText("Se Procedera A Ir Al Formulario Compras");
        jButton1.setDoubleBuffered(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Idproducto:");
        jLabel1.setDoubleBuffered(true);

        txtidproducto.setEditable(false);
        txtidproducto.setDoubleBuffered(true);
        txtidproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidproductoKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");
        jLabel2.setDoubleBuffered(true);

        txtnombre.setDoubleBuffered(true);
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtstock.setDoubleBuffered(true);
        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstockKeyTyped(evt);
            }
        });

        txtvalunitario.setDoubleBuffered(true);
        txtvalunitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalunitarioKeyTyped(evt);
            }
        });

        jLabel3.setText("ValorUnitario");
        jLabel3.setDoubleBuffered(true);

        jLabel4.setText("Stock:");
        jLabel4.setDoubleBuffered(true);

        jLabel5.setText("Concepto:");
        jLabel5.setDoubleBuffered(true);

        jTextPane1.setDoubleBuffered(true);
        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jLabel6.setText("Marca:");
        jLabel6.setDoubleBuffered(true);

        txtmarca.setDoubleBuffered(true);
        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        jLabel7.setText("Modelo:");
        jLabel7.setDoubleBuffered(true);

        txtmodelo.setDoubleBuffered(true);
        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmodeloKeyTyped(evt);
            }
        });

        jLabel8.setText("Procesador:");
        jLabel8.setDoubleBuffered(true);

        txtmemoriainterna.setDoubleBuffered(true);
        txtmemoriainterna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmemoriainternaKeyTyped(evt);
            }
        });

        jLabel9.setText("Memoria Interna:");
        jLabel9.setDoubleBuffered(true);

        txtmemoriaexterna.setDoubleBuffered(true);
        txtmemoriaexterna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmemoriaexternaKeyTyped(evt);
            }
        });

        jLabel10.setText("Memoria Externa:");
        jLabel10.setDoubleBuffered(true);

        txtprocesador.setDoubleBuffered(true);
        txtprocesador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprocesadorKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_78348.png"))); // NOI18N
        jButton2.setText("Registrar");
        jButton2.setDoubleBuffered(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/garbage_78344.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setDoubleBuffered(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize_78340.png"))); // NOI18N
        jButton4.setText("Actualizar");
        jButton4.setDoubleBuffered(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo:");
        jLabel11.setDoubleBuffered(true);

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tecnologia", "accesorio", "otro" }));
        cmbtipo.setDoubleBuffered(true);

        jLabel12.setText("Gama:");
        jLabel12.setDoubleBuffered(true);

        cmbgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alta", "mediaAlta", "media", "mediaBaja", "baja" }));
        cmbgama.setDoubleBuffered(true);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Buscar Producto");
        jLabel13.setDoubleBuffered(true);

        jLabel14.setText("Nombre:");
        jLabel14.setDoubleBuffered(true);

        jTextnomProduc.setDoubleBuffered(true);
        jTextnomProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextnomProducKeyTyped(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loupe_78347.png"))); // NOI18N
        jButton5.setText("Buscar");
        jButton5.setDoubleBuffered(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setDoubleBuffered(true);
        jScrollPane3.setViewportView(jTable1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archives_78380.png"))); // NOI18N
        jButton6.setText("Cargar");
        jButton6.setDoubleBuffered(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transfer_77884.png"))); // NOI18N
        jButton7.setText("Ventas");
        jButton7.setDoubleBuffered(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(253, 253, 253))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextnomProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(txtvalunitario)
                                    .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtmemoriainterna, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel10)
                                                    .addComponent(txtmemoriaexterna, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbgama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmemoriainterna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmemoriaexterna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprocesador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidproducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvalunitario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(62, 62, 62)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextnomProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel14)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
        FormCompras frt = new FormCompras();
        frt.setEnabled(true);
        frt.setVisible(true);
        if (ldcfinal instanceof DetalleCompra) {
            frt.setLdc(ldcfinal);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Producto pdc = Producto.getInstance();
        if ((!"".equals(txtnombre.getText()) && Integer.parseInt(txtidproducto.getText()) == 0) && pdc instanceof Producto) {
            pdc.setGama(cmbgama.getSelectedItem().toString());
            pdc.setMarca(txtmarca.getText());
            pdc.setMemoriaExterna(txtmemoriainterna.getText());
            pdc.setMemoriaInterna(txtmemoriaexterna.getText());
            pdc.setModelo(txtmodelo.getText());
            pdc.setNombre(txtnombre.getText());
            pdc.setProcesador(txtprocesador.getText());
            pdc.setTipo(cmbtipo.getSelectedItem().toString());
            pdc.setValor(Double.parseDouble(txtvalunitario.getText()));
            pdc.setDescripcion(jTextPane1.getText());
            pdc.setStock(Integer.parseInt(txtstock.getText()));
            pdc.setIdProducto(Integer.parseInt(txtidproducto.getText()));
            pdc.start();
            ClaseMensaje.miMensajeAprovado();
            txtnombre.setText("");
            txtvalunitario.setText("");
            txtmarca.setText("");
            txtmodelo.setText("");
            txtprocesador.setText("");
            txtmemoriaexterna.setText("");
            txtmemoriainterna.setText("");
            jTextPane1.setText("");
            txtstock.setText("");
            txtidproducto.setText("0");
        } else {
            ClaseMensaje.miMensajeError();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Producto pdc = Producto.getInstance();
        if (Integer.parseInt(txtidproducto.getText()) > 0 && pdc instanceof Producto) {
            pdc.setIdProducto(Integer.parseInt(txtidproducto.getText()));
            pdc.start();
            ClaseMensaje.miMensajeEliminado();
            txtidproducto.setText("0");
        } else {
            ClaseMensaje.miMensajeError();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Producto pdc = Producto.getInstance();
        if ((!"".equals(txtnombre.getText()) && Integer.parseInt(txtidproducto.getText()) > 0) && pdc instanceof Producto) {
            pdc.setIdProducto(Integer.parseInt(txtidproducto.getText()));
            pdc.setGama(cmbgama.getSelectedItem().toString());
            pdc.setMarca(txtmarca.getText());
            pdc.setMemoriaExterna(txtmemoriainterna.getText());
            pdc.setMemoriaInterna(txtmemoriaexterna.getText());
            pdc.setModelo(txtmodelo.getText());
            pdc.setNombre(txtnombre.getText());
            pdc.setProcesador(txtprocesador.getText());
            pdc.setTipo(cmbtipo.getSelectedItem().toString());
            pdc.setValor(Double.parseDouble(txtvalunitario.getText()));
            pdc.setDescripcion(jTextPane1.getText());
            pdc.setStock(Integer.parseInt(txtstock.getText()));
            pdc.start();
            ClaseMensaje.miMensajeActualizado();
            txtidproducto.setText("0");
            txtstock.setText("");
            txtnombre.setText("");
            txtvalunitario.setText("");
            txtmarca.setText("");
            txtmodelo.setText("");
            txtprocesador.setText("");
            txtmemoriaexterna.setText("");
            txtmemoriainterna.setText("");
            jTextPane1.setText("");
        } else {
            ClaseMensaje.miMensajeError();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        BuscarProducto bp = new BuscarProducto();
        bp.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtidproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidproductoKeyTyped
        // TODO add your handling code here:
        evalnum(evt);
    }//GEN-LAST:event_txtidproductoKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtvalunitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalunitarioKeyTyped
        // TODO add your handling code here:
        evalnumdec(evt);
    }//GEN-LAST:event_txtvalunitarioKeyTyped

    private void txtstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyTyped
        // TODO add your handling code here:
        evalnum(evt);
    }//GEN-LAST:event_txtstockKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txtmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtmodeloKeyTyped

    private void txtprocesadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprocesadorKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtprocesadorKeyTyped

    private void txtmemoriaexternaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemoriaexternaKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtmemoriaexternaKeyTyped

    private void txtmemoriainternaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemoriainternaKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_txtmemoriainternaKeyTyped

    private void jTextPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane1KeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_jTextPane1KeyTyped

    private void jTextnomProducKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnomProducKeyTyped
        // TODO add your handling code here:
        evaltextYnum(evt);
    }//GEN-LAST:event_jTextnomProducKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtidproducto.setText(jTable1.getValueAt(row, 0).toString());
        txtnombre.setText(jTable1.getValueAt(row, 6).toString());
        jTextPane1.setText(jTable1.getValueAt(row, 10).toString());
        txtstock.setText(jTable1.getValueAt(row, 11).toString());
        txtvalunitario.setText(jTable1.getValueAt(row, 9).toString());
        txtmarca.setText(jTable1.getValueAt(row, 2).toString());
        txtmodelo.setText(jTable1.getValueAt(row, 5).toString());
        cmbtipo.setSelectedItem(jTable1.getValueAt(row, 8).toString());
        cmbgama.setSelectedItem(jTable1.getValueAt(row, 1).toString());
        txtprocesador.setText(jTable1.getValueAt(row, 7).toString());
        txtmemoriaexterna.setText(jTable1.getValueAt(row, 4).toString());
        txtmemoriainterna.setText(jTable1.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
        FrmVentas frt = new FrmVentas();
        frt.setEnabled(true);
        frt.setVisible(true);
        if (ldvfinal instanceof DetalleVenta) {
            frt.setLdv(ldvfinal);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrmPrincipal frd = new FrmPrincipal();
        frd.setEnabled(true);
        frd.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed
    @Override
    public void evaltextYnum(java.awt.event.KeyEvent tyea) {
        char c = tyea.getKeyChar();
        if ((c < '0' || c > '9') & (c < 'A' || c > 'Z') & (c < 'a' || c > 'z') & (c < '.' || c > '.') & (c < ' ' || c > ' ')) {
            tyea.consume();
        }
    }

    @Override
    public void evalnumdec(java.awt.event.KeyEvent ohynu) {
        char c = ohynu.getKeyChar();
        if ((c < '0' || c > '9') & (c < '.' || c > '.')) {
            ohynu.consume();
        }
    }

    @Override
    public void evalnum(java.awt.event.KeyEvent ohynu) {
        char c = ohynu.getKeyChar();
        if ((c < '0' || c > '9')) {
            ohynu.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbgama;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField jTextnomProduc;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmemoriaexterna;
    private javax.swing.JTextField txtmemoriainterna;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprocesador;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txtvalunitario;
    // End of variables declaration//GEN-END:variables
private class BuscarProducto extends Thread {

        @Override
        public void run() {
            Basededatos bd = Basededatos.getInstance();
            try {
                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("IdProducto");
                modelo.addColumn("gama");
                modelo.addColumn("Marca");
                modelo.addColumn("MemoriaExterna");
                modelo.addColumn("MemoriaInterna");
                modelo.addColumn("Modelo");
                modelo.addColumn("Nombre");
                modelo.addColumn("Procesador");
                modelo.addColumn("Tipo");
                modelo.addColumn("Valor");
                modelo.addColumn("Descripcion");
                modelo.addColumn("Stock");
                jTable1.setModel(modelo);
                if (bd.conectar() != null) {

                    String sql = "Select * from Producto where nombre like '%" + jTextnomProduc.getText() + "%'";

                    Statement ps = bd.conn.createStatement();
                    ResultSet rs = ps.executeQuery(sql);

                    while (rs.next()) {
                        Object[] dato1 = new Object[]{
                            rs.getInt("idproducto"),
                            rs.getString("gama"),
                            rs.getString("marca"),
                            rs.getString("memoriaExterna"),
                            rs.getString("memoriaInterna"),
                            rs.getString("modelo"),
                            rs.getString("nombre"),
                            rs.getString("procesador"),
                            rs.getString("tipo"),
                            rs.getDouble("valor"),
                            rs.getString("descripcion"),
                            rs.getInt("stock")};
                        modelo.addRow(dato1);
                    }

                    jTable1.setModel(modelo);
                    bd.desconectar();
                    //la lista

                }
            } catch (SQLException e) {
                Logger.getLogger(FrmInventario.class.getName()).log(Level.SEVERE, null, e);

            }
            try {
                this.stop();

            } catch (Exception ex) {
                Logger.getLogger(FrmInventario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
}
